console.log("Service Worker Loaded...");

self.addEventListener("push", (e) => {
    let options = {
        body:"this notification is generated by web push notification",
        icon:"",
        vibrate:[100,50,100],
        data:{
            dateOfArrival:Date.now(),
            primaryKey:'1'
        },
        actions:[
            {
                action:'explore',title:'explore',icon:''
            },
            {
                action:'close',title:'close',icon:''
            }
        ]
    }
e.waitUntill(
    self.registration.showNotification('hello user',options)
);

});